// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSteamPlayerInfo(arg1:string):Promise<main.SteamProfile>;

export function Greet(arg1:string):Promise<string>;

export function OpenSaveFile():Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
